language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t arnabc/docker-devops-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true arnabc/docker-devops-1 npm run test -- --coverage
